services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432" # host:container to avoid conflicts on 5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://app:app@db:5432/app?schema=public"
      NEXTAUTH_SECRET: "replace-me"
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "development"
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
